Store all job in yaml
zaikio/zaikio-mission_control-ruby pull request #33
Opened 2023-11-10 14:27 UTC by YannIsCoding

2023-11-10 14:28 UTC, YannIsCoding commented on lib/zaikio/mission_control/jobs/jobs.yml
> +banner:
I just stuffed this here, there is probably a better place for it. Open to suggestion.

2023-11-10 15:48 UTC, jalyna requested changes
lgtm, just one issue I have identified

2023-11-10 15:48 UTC, jalyna commented on lib/zaikio/mission_control/jobs/base.rb
> +        jobs = YAML.load_file("lib/zaikio/mission_control/jobs/jobs.yml", symbolize_names: true)
I think this path won't work when the gem is used in a rails app. This is for example how we do it in the toolkit for loading the countries.yml

```rb
YAML.safe_load(File.open(File.join(File.dirname(__FILE__), "../../../config/countries.yml")))
```

2023-11-13 08:03 UTC, YannIsCoding commented on lib/zaikio/mission_control/jobs/base.rb
> +        jobs = YAML.load_file("lib/zaikio/mission_control/jobs/jobs.yml", symbolize_names: true)
Thanks for the valuable feedback! 
It looks like `YAML.safe_load(File.open..)` can be replaced by `YAML.safe_load_file.`. I'll do this as it is a little nicer to read 😄

2023-11-13 09:05 UTC, jalyna approved these changes

2023-11-13 09:05 UTC, jalyna commented on lib/zaikio/mission_control/jobs/base.rb
> +        jobs = YAML.safe_load_file(File.join(File.dirname(__FILE__), "jobs.yml"), symbolize_names: true)
My last feedback on this - but not blocking.
I would suggest that we move such configurations to a dedicated `config/` folder instead of hiding in `lib/`. wdyt? This would also create more consistency between other projects. I personally believe yml files should never be in lib.

2023-11-13 09:09 UTC, YannIsCoding commented on lib/zaikio/mission_control/jobs/base.rb
> +        jobs = YAML.safe_load_file(File.join(File.dirname(__FILE__), "jobs.yml"), symbolize_names: true)
That was exactly the kind of feedback I was after 😉 https://github.com/zaikio/zaikio-mission_control-ruby/pull/33#discussion_r1389473086

yeah that sounds good. I'll do `config/data` for extra clarity.

2023-11-13 09:11 UTC, jalyna commented on lib/zaikio/mission_control/jobs/base.rb
> +        jobs = YAML.safe_load_file(File.join(File.dirname(__FILE__), "jobs.yml"), symbolize_names: true)
💯

2023-11-13 09:44 UTC, merged